### ISSUE TITLE
New environment missing predefined_attributes

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm#118]
Source for predefined attributes
https://github.com/City-of-Helsinki/helerm/blob/master/metarecord/models/predefined_attributes.py

Issue may be in this code
https://github.com/City-of-Helsinki/helerm/blob/master/metarecord/models/attribute.py

NOTE   'identifier': 'PhaseType', needs value list before first TOS-Excel import
Other attribute values will be collected from TOS-Excel content.

**Comment by mikkokeskinen** [comment]
Have you imported the initial data?

https://github.com/City-of-Helsinki/helerm#import

**Comment by vikoivun** [comment]
Now done, thank you!

**Comment by Ta1Nur** [comment]
Readme had that all in todo https://github.com/City-of-Helsinki/helerm/blob/master/README.md
Attributes, classifications and also functions, done.
