### ISSUE TITLE
Implement ability to fetch a navigation tree

### ISSUE THREAD

**Issue by tuomas777** [City-of-Helsinki/helerm#13]
The frontend requires a navigation tree of the Functions. The navigation tree should be returned in format 
```
{  
   "id": <>, 
   "function_id": <>, 
   "name" <>, 
   "children": [
       { 
         "id": <>, 
         "function_id": <>, 
         "name": <>, 
         "children": []
       } 
   ] 
}
```

**Comment by juyrjola** [comment]
I don't see a good reason for nested resources. The frontend should be able to generate the hierarchy based on `parent` information.

**Comment by tuomas777** [comment]
in frontend it is, closing
