### ISSUE TITLE
New validation rules 

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm#133]
Rule 1) When RetentionPeriod = "-1",  "RetentionPeriodStart" not required and should be empty 
Rule 2) Additional requirement to current rule -> When PublicityClass = "Julkinen" , "SecurityPeriod", "SecurityReason", "Restriction.SecurityPeriodStart" not required and should be empty
Rule 3) When "StorageLocation not empty, "RetentionPeriodOffice" "StorageAccountable", "StorageOrder", "ProtectionClass" required
Rule 4) Related to rule 3 "StorageLocation", "RetentionPeriodOffice" "StorageAccountable", "StorageOrder", "ProtectionClass" if one then all, else all empty. (corrected rule 7/12)
Rule 5) Add mandatory attribute "SocialSecurityNumber"for Record, Function

Finnish US https://tree.taiga.io/project/juyrjola-tiedonohjausjarjestelma/us/273

**Comment by tuomas777** [comment]
Also:

* RetentionReason and SecurityReason should not be multivalued attributes
* Multivalued enum attributes should allow values outside enum choices
