### ISSUE TITLE
Add missing complex validation rules to attribute JSON Schema

### ISSUE THREAD

**Issue by tuomas777** [City-of-Helsinki/helerm#144]

**Comment by Ta1Nur** [comment]
Attributes validation 
Software architecture needs full review in Spring 2018  - new rules added 12/2017
NOW postponed "Add new validation type all_or_none" complex validation rules to attribute JSON Schema

**Comment by Ta1Nur** [comment]
JSON schema alternative in issue #198 We close this for now.
