### ISSUE TITLE
Serve REST API data as XML on demand

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#193]
See what it requires to implement XML API to compliment the current REST API to serve wider variety of clients.

Decide format depending on request GET parameter value. For example `format=xml` and `format=json`. Default to JSON.

**Comment by Ta1Nur** [comment]
@japauliina additional information in slack about current xml export.

**Comment by Ta1Nur** [comment]
We can go trough use cases on Wednesday and discuss more about this then.

**Comment by Ta1Nur** [comment]
👍
