### ISSUE TITLE
Improve Django admin views

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#194]
The current Django admin views are pretty barebones and that makes them somewhat inefficient to use. Improve UX by adding any relevant columns to the list views and implement list view filters. Basically any quality-of-life / ease-of-use improvements that can be easily implemented with the tools offered  by Django.

**Comment by Ta1Nur** [comment]
Tested and helps i.e. function filtering "00 04 05"
Select Classification_code (Tunnus)
![image](https://user-images.githubusercontent.com/14962739/45406042-d79ed000-b66d-11e8-9269-eca64810c64d.png)

**Comment by ehaivala** [comment]
Resolved in #196
