### ISSUE TITLE
Delete Function drafts when saving as public

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#195]
Drafts of a `Function` model instance should be deleted permanently instead of soft deletion. Currently delete request to the Function API endpoint changes the instance state to `deleted` effectively soft deleting the instance. Replace this soft delete logic with real deletion.

**Comment by ehaivala** [comment]
How/when the deletion should be done? Some options on how to approach this:

1. Draft is deleted manually from the UI.

2. Delete all prior drafts for approved `Function` automatically when it is approved.

3. In batches at set intervall. Delete all drafts that are superseded by approved version.

**Comment by Ta1Nur** [comment]
1. No manual delete needed - or will be implemented to this
2. This option 2. is the most wanted solution
3. If more easy than option 2,  we can discuss about it.
