### ISSUE TITLE
Manageable attribute validation

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#198]
Attribute validation is currently hard coded to the model classes. This should be somehow manageable in the future.

Maybe replace the current hard coded dictionaries with a model that has unique selection field for which model it implements the validation rules for. The model could have M2M relation for different attribute categories (allowed, required, etc) from which the dictionary/JSON representation is formed from.

**Comment by Ta1Nur** [comment]
Sounds good.

**Comment by klemmari1** [comment]
Implemented in https://github.com/City-of-Helsinki/helerm/pull/293
