### ISSUE TITLE
Check JHS 191 XML export data

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#199]
Check what data is being exported in JHS 191 XML and compile a list of missing data that is supposed to be in the XML.

**Comment by Ta1Nur** [comment]
I did check content uses one classification and function where I have now JHS 191 elements in function content. It is draft so it needs authentication in development environment https://api.hel.fi/helerm-dev/v1/function/da21cd4a5c4c4da3a605f8eb2a2cb6eb/ - for classification I did add custom fields now. When I get this content in JSON or XML format I can easily check it.

**Comment by Ta1Nur** [comment]
Export checks and updates in feature requests for now. We close this for now.
