### ISSUE TITLE
JSH 191 XML export improvements

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#200]
This issue contains multiple sub tasks.

### 1. Authentication

Unauthenticated export should not include names, version numbers, or any confidential data.

### 2. Export only valid and approved data

* Export only data that is valid at the time of export. `Function` has `valid_from` and `valid_to` fields that can be used to check the validity of a `Function` instance.
* Export only `Function`s that are in approved state.

### 3. Changes in exported data

Update exporter to include all missing data specified in issue #199.

**Comment by Ta1Nur** [comment]
Can we implement this optional, so if there is no dates valid_from and valid_to in approved version, it still show latest approved version. -> hopefully this can give time to implement this valid period to function content.

Also we will have function with only valid_from date, current approved version. Until we make next version of that function content.

**Comment by ehaivala** [comment]
Some features I discovered while taking a closer look at the export:

* Exporting with `state=approved` GET parameter will yield only approved Functions
* Exporting with `valid_at=YYYY-MM-DD` GET parameter will yield only Functions that are valid at the given time

This functionality is already implemented.

**Comment by ehaivala** [comment]
Require authentication for the current export view to compliment cached "public" export specified in issue #202.
