### ISSUE TITLE
REST API filtering options

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#201]
Filter rules for `Function` endpoint:

### 1. Classification code

Filter by `Function.classification.code` so end users can easily search by classification codes like "01 02 03".

### 2. Validity

Filter by `Function` validity. I.e. given date is between `valid_from` and `valid_to`. This apparently is already implemented but check how it works and document it somewhere.

### 3. Information system

Filter by related `Record` `InformationSystem` attribute value. 

```python
Record.objects.filter(attributes__InformationSystem__icontains='ahjo')
```

### 4. Latest approved

Add option to filter out all but latest approved versions. Queryset filtering exists already but add the option to API endpoint as well.

```python
Function.objects.latest_approved()
```

**Comment by Ta1Nur** [comment]
👍
