### ISSUE TITLE
Cache JHS 191 XML export

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#202]
Exported XML doesn't need to contain the very latest data. Generating the XML data takes a while and someone bombarding the export view can quite easily bring the database to its knees.

Cache JHS 191 XML data and export from cache on demand. Update cache every 12 hours with a scheduled task.

**Comment by Ta1Nur** [comment]
👍

**Comment by ehaivala** [comment]
Let's implement separate endpoint that serves approved and public information that doesn't require authentication and doesn't implement any filtering. That can then be cached to improve of the export.

**Comment by japauliina** [comment]
Change to the cache update cycle: update the cache every 6 hours (9,15,21,03).
