### ISSUE TITLE
helerm data model -English and Finnish

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm#22]
Would it be useful to have current back end data model graph/schema available here in GitHub? For users, product manager, for front developer and API clients?

After that current model English version it may be useful to have it in both languages and perhaps compared to JHS 191 what will be extremely useful API client system developers.

Attached Finnish JHS 191 model picture - only Finnish (English terms received from SÄHKE2, if not in there has HKI translation approved by our records management specialists).
![tietomalli](https://cloud.githubusercontent.com/assets/14962739/21605318/15bd180e-d1b1-11e6-8e6d-f00de9c2916c.PNG)

Resources in Finnish
Link to JHS 191 Recommendation http://www.jhs-suositukset.fi/web/guest/jhs/recommendations/191
Link to SÄHKE2 Norm (legal) http://www.arkisto.fi/fi/palvelut/normit/maeaeraeykset/saehke2-maeaeraeys

**Comment by juyrjola** [comment]
Use `graph_models` management command in `django_extensions`.

**Comment by tuomas777** [comment]
Initial models pic created using `graph_models`

![pic](https://cloud.githubusercontent.com/assets/1314604/22827147/ffeecda4-ef9e-11e6-94fb-68a2034e353c.png)

**Comment by Ta1Nur** [comment]
Explain JHS 191 metamodel element action (fi toimenpide)- can be only one level "phase" - "records" or two level "phase" (fi käsitelyvaihe) - "action" (fi toimenpide) - "records" (fi asiakirjatieto)

**Comment by Ta1Nur** [comment]
First version of datamodel in this issue. Next level will be available later and also datamodel will be available http://iow.csc.fi/model/hkitos/ in near future for interoperability purposes and discussions in national level.
