### ISSUE TITLE
Ahjo JHS XML export

### ISSUE THREAD

**Issue by japauliina** [City-of-Helsinki/helerm#220]
There is a need for JHS XML Ahjo specific export. This export should be generated in the same way as the already existing JHS export, but with the following differences:
- The export only contains functions that have “Ahjo” in their `InformationSystem` attribute.
- The export should not contain `Toimenpidetiedot` attribute.

The endpoint for this export should be visible in API Root.

Ahjo export should also be cached in the same way as in issue #202.

**Comment by Ta1Nur** [comment]
Export checks and updates in feature requests for now. We close this for now.
