### ISSUE TITLE
Update to Django 2.2

### ISSUE THREAD

**Issue by ehaivala** [City-of-Helsinki/helerm#230]
Django 2.2 (LTS) was released on 1st of April. Update the API to use that instead of current Django 2.0.

**Comment by ehaivala** [comment]
The update is relatively painless. Only catch I'm aware of is the changed behavior with django-filter with invalid date query parameters. So there might be issues with the UI depending on how it handles the filtering.

Previously the API responded to invalid dates with empty result set and status code 200. Now the response is an error message with status code 400.

The current progress is in [`django-update`](https://github.com/City-of-Helsinki/helerm/compare/django-update) branch. It should be more or less done already based on my limited testing.

**Comment by ehaivala** [comment]
I haven't tested authentication and I'm not sure how it is affected by this update. Someone who know the Helsinki authentication better should check it out.

**Comment by vikoivun** [comment]
I don't expect authentication to have issues. I propose we test that in dev.

**Comment by Ta1Nur** [comment]
Updated #239
