### ISSUE TITLE
JHS 191 XML exporter small fixes

### ISSUE THREAD

**Issue by Jogha** [City-of-Helsinki/helerm#248]
Due to Ahjo integration, we do have few changes that needs to be implemented.

- Include all Classifications, even is there is no approved functions
- Add "SailytysAjanLaskentaperuste" -field to XML

**Comment by Ta1Nur** [comment]
OpenApi.yaml 
fix link http://www.jhs-suositukset.fi/web/guest/jhs/recommendations/191
add link to tech

**Comment by Jogha** [comment]
OpenApi naming conventions are pretty misleading in this case. The field name is `externalDocs`, but it is possible to add only one external document to the path object.

https://swagger.io/specification/#externalDocumentationObject
