### ISSUE TITLE
Check PhaseType only for Phase and ActionType only for Action

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm#52]
New Optional attributes are in all levels also in function and in record.
See screenshot from function level
![2017-04-06_tyypit_kohdennus](https://cloud.githubusercontent.com/assets/14962739/24752264/bf666352-1ad5-11e7-9887-e557cf7ee223.PNG)

**Comment by tuomas777** [comment]
Attribute schema from backend has `PhaseType` only for `Phase` and `ActionType` only for `Action`, so this seems to be an UI issue.

**Comment by Ta1Nur** [comment]
Ok, I will discuss with UI developers tomorrow 👍

**Comment by Ta1Nur** [comment]
UI developers will correct this when new edit forms and features are ready.
