### ISSUE TITLE
Delete draft versions functionality

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm#85]
Typically useful when i.e. drafted function - if started and not going to be used/approved.
Also will help when current versioning allow save drafts without locking. 
In approval process drafts can be removed when function is approved.

We can limit deletion because all modifications to content only allowed only draft versions.

**Comment by tuomas777** [comment]
Decided to go with soft deletion.

**Comment by mikkokeskinen** [comment]
A user should be able to delete their own drafts. Should add a permission which will allow deleting of other users drafts too.
