### ISSUE TITLE
Add support for multivalued attributes

### ISSUE THREAD

**Issue by tuomas777** [City-of-Helsinki/helerm#94]
Some attributes should be able to have multiple values. Currently this is not possible, as the attributes for structural elements are stored in hstore, where values are just strings.

Possible solutions:
  - add those attributes as actual fields for the models
  - change attributes hstore to jsonfield and use a list as the value instead of a string

**Comment by mikkokeskinen** [comment]
Remember to update swagger spec too.

**Comment by Ta1Nur** [comment]
Just reminding that current and also when data is imported from Excel is only text form, so hopefully this structure can handle that not value based text information ecspecially when fuction is draft. Users will update field values in ui. Use case they read text what is in that attribute field and choose correct values from the list of ie. InformationSystem values. In UI it is quite challenging to make not prevalued free text and select element, but let us see if we manage to get it in October with UI developers. # #

**Comment by Ta1Nur** [comment]
This is ready - done by @tuomas777 I will close this issue.
